MVCLayoutViews/Controllers/NareshITController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLayoutViews.Controllers
{
    public class NareshITController : Controller
    {
        public ViewResult Home()
        {
            return View();
        }
        public ViewResult Register()
        {
            return View();
        }
        public ViewResult Login()
        {
            return View();
        }
        public ViewResult Courses()
        {
            return View();
        }
        public ViewResult About()
        {
            return View();
        }
    }

}

MVCLayoutViews/Views/NareshIT/About.cshtml
@{
    ViewBag.Title = "About Page";
}

<p style="text-align: justify; color: green; font-family: 'Agency FB'; text-transform: capitalize; text-indent:
50px;font-size:25px">
    NareshIT (Naresh I Technologies) is a leading Software Training Institute and provides Job
    Guarantee Program through Nacre in Hyderabad, Chennai, Bangalore, Vijayawada and across the world with Online
    Training services. Managed and Lead by IT Professionals with more than a decade experience in leading MNC
    companies. We are most popular for our training approach that enables students to gain real-time exposure on
    cutting-edge technologies. Naresh I Technologies started satisfying the students who are at remote locations with
    Online Training program, with an intention to provide services for all those aspirants who want to be part of the
    software industry. The aspirants who due to various reasons cannot travel physically to our location can just keep
    themselves registered for this program along with their needs with just a single phone call or a mail provided in our
    contact’s page. The Online Training program is conducted over the internet using the latest state of the art software
    tools and via the video and desktop sharing facility. The training program is conducted by well experienced training
    faculty who are mentored in conducting such sessions as per the convenience of the participant. The Online
    Training program is provided with required material for reference and on hands exercises and Lab sessions for
    practical exposure. The students are monitored for any clarifications and doubts by the faculty all through the
    course either by phone or mail as per the convenience of the participants. Our sole maxim in introducing Online
    Technical Training Sessions is to cater to the training requirements of the aspirants who due to various reasons
    cannot travel physically to our location. In the online training program, the training sessions are conducted over the
    internet using the latest state of the art software tools and the hands-on experience also will be provided at the
    convenience of the participant.
</p>

@section s1{
    <p>Lab Grown diamonds are much more viable and eco friendly than mining natural diamonds</p>
    }

MVCLayoutViews/Views/NareshIT/Courses.cshtml
@{
    ViewBag.Title = "Courses Page";
}

<h2>Courses Offered:</h2>
<ul type="square">
    <li>.NET</li>
    <li>Java</li>
    <li>Python</li>
    <li>DevOps</li>
    <li>Selenium</li>
    <li>Cloud Technologies</li>
    <li>Data Science</li>
    <li>Automation</li>
    <li>Software Testing</li>
    <li>Mobile Technologies</li>
    <li>Digital Marketing</li>
    <li>Spring Boot & Microservices</li>
</ul>
@section S1 {
    <font size="3" color="blue">Experienced faculties with excellent training skills.</font>
}

MVCLayoutViews/Views/NareshIT/Home.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_SiteMaster.cshtml";
}

<p style="text-align: justify; color: palevioletred; font-family: Arial; text-indent: 50px">
    We have set the pace with
    online learning. Learn what you want, when you want, and practice with the instructor-led training sessions,
    on-demand video tutorials which you can watch and listen.
</p>
<ol style="color:blueviolet; background-color: darkseagreen">
    <li>150+ Online Courses</li>
    <li>UNLIMITED ACCESS</li>
    <li>EXPERT TRAINERS</li>
    <li>ON-THE-GO-LEARNING</li>
    <li>PASSIONATE TEAM</li>
    <li>TRAINING INSTITUTE OF CHOICE</li>
</ol>
<p style="text-align: justify; color: palevioletred; font-family: Arial; text-indent: 50px">
    Naresh I Technologies is
    renowned around the world for classroom training where every aspirant is encouraged to attend technical sessions
    discussing every facet of the subject with excruciating detail on varied technologies. Every aspirant in the training
    program will be provided with the hands-on experience through several Lab assignments and case studies there by
    making them more employable.
</p>

@section S1 {
    <font size="3" color="blue">Excellence in IT Training since 2003.</font>
}

MVCLayoutViews/Views/NareshIT/Login.cshtml
@{
    ViewBag.Title = "Login Page";
}

<h3 style="text-align:center;text-decoration:underline">Login Page</h3>
<table class="table-bordered" align="center">
    <tr><td>User Id:</td><td><input type="text" id="txtUid" /></td></tr>
    <tr><td>Password:</td><td><input type="password" id="txtPwd" /></td></tr>
    <tr>
        <td colspan="2" align="center">
            <input type="submit" id="btnLogin" value="Login" />
            <input type="reset" id="btnReset" value="Reset" />
        </td>
    </tr>
</table>
@section S1 {
    <font size="3" color="blue">Trained over 10,00,000 IT Professionals.</font> 
    }

MVCLayoutViews/Views/NareshIT/Register.cshtml
@{
    ViewBag.Title = "Registration Page";
}

<h3 style="text-align:center;text-decoration:underline">Registration Page</h3>
<table align="center" class="table-bordered">
    <tr>
        <td>Name:</td>
        <td><input type="text" id="txtName" /></td>
    </tr>
    <tr>
        <td>User Id:</td>
        <td><input type="text" id="txtUid" /></td>
    </tr>
    <tr>
        <td>Password:</td>
        <td><input type="password" id="txtPwd" /></td>
    </tr>
    <tr>
        <td>Confirm Password:</td>
        <td><input type="password" id="txtCPwd" /></td>
    </tr>
    <tr>
        <td>Mobile:</td>
        <td><input type="tel" id="txtMobile" /></td>
    </tr>
    <tr>
        <td>Email Id:</td>
        <td><input type="email" id="txtEmail" /></td>
    </tr>
    <tr>
        <td colspan="2" align="center">
            <input type="submit" id="btnRegister" value="Register" />
            <input type="reset" id="btnReset" value="Reset" />
        </td>
    </tr>
</table>
@section S1 {
    <font size="3" color="blue">Join us for best IT Training.</font>
}

MVCLayoutViews/Views/Shared/_SiteMaster.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title -NIT</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div> 
        <table style="width:100%">
            <tr>
                <td align="center" style="background-color:beige">
                    <img  src="~/Images/logo.jpg" class="rounded-circle" style="height:100px;width:100px" />
                </td>
                <td>
                    <img src="~/Images/header.jpg" style="height:100px;width:100%" class="rounded"/>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;background-color: burlywood">
                    <nav  class="navbar-dark bg-primary">
                        <font size="4">
                            @Html.ActionLink("Home Page", "Home", "NareshIT", new { @class = "navbar-brand" })<br />
                            @Html.ActionLink("Registration Page", "Register", "NareshIT", new { @class = "navbar-brand" })<br />
                            @Html.ActionLink("Login Page", "Login", "NareshIT", new { @class = "navbar-brand" })<br />
                            @Html.ActionLink("Courses Offered", "Courses", "NareshIT", new { @class = "navbar-brand" })<br />
                            @Html.ActionLink("About Us", "About", "NareshIT", new { @class = "navbar-brand" })<br />
                        </font>
                    </nav>
                </td>
                <td>
                    @RenderBody()
                </td>
            </tr>
            <tr>
                <td colspan="2" style="background-color:coral;text-align:center">
                    @RenderSection("S1", false)
                </td>
            </tr>
            <tr>
                <td colspan="2" style="width:100%">
                    <img src="~/Images/footer.jpg" style="width:100%;height:150px"/>
                </td>
            </tr>
        </table>
    </div>
</body>
</html>